function report9 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  REPORT9 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  REPORT9 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  report9 = importfile("C:\Users\Pablo\Desktop\trabajo\DeepJanus\Experiments\guided\9\report9.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-May-2023 09:43:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["run", "iteration", "timestamp", "archive_len", "total_seeds", "covered_seeds", "finalSeeds", "LWT_min", "LWT_max", "LWT_avg", "LWT_std", "members_dist_min", "members_dist_max", "members_dist_avg", "members_dist_std"];
opts.VariableTypes = ["double", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitvar";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "timestamp", "InputFormat", "HH:mm:ss");

% Import the data
report9 = readtable(filename, opts);

end